%Find missing values
TF_GroundTransportation=ismissing(airport_dataset.GroundTransportationTo_fromAirport);
airport_dataset.GroundTransportationTo_fromAirport=fillmissing(airport_dataset.GroundTransportationTo_fromAirport,"movmedian",10);

TF_ParkingFacilities=ismissing(airport_dataset.ParkingFacilities)
%airport_dataset.ParkingFacilities=fillmissing(airport_dataset.ParkingFacilities,"movmedian",10);

TF_ParkingFacilities_VfM=ismissing(airport_dataset.ParkingFacilities_valueForMoney_);
%airport_dataset.ParkingFacilities_valueForMoney_=fillmissing(airport_dataset.ParkingFacilities_valueForMoney_,"movmedian",10);

TF_BagaggeCarts=ismissing(airport_dataset.AvailabilityOfBaggageCarts);
%airport_dataset.AvailabilityOfBaggageCarts=fillmissing(airport_dataset.AvailabilityOfBaggageCarts,"movmedian",10);

TF_EfficiencyCheckinStaff=ismissing(airport_dataset.EfficiencyOfCheck_inStaff);
%airport_dataset.EfficiencyOfCheck_inStaff=fillmissing(airport_dataset.EfficiencyOfCheck_inStaff,"movmedian",10);


TF_CheckingWaittime=ismissing(airport_dataset.Check_inWaitTime);
%airport_dataset.Check_inWaitTime=fillmissing(airport_dataset.Check_inWaitTime,"movmedian",10);

TF_CourtesyCheckinStaff=ismissing(airport_dataset.CourtesyOfOfCheck_inStaff);
%airport_dataset.CourtesyOfOfCheck_inStaff=fillmissing(airport_dataset.CourtesyOfOfCheck_inStaff,"movmedian",10);

TF_WaitTimePassport=ismissing(airport_dataset.WaitTimeAtPassportInspection);
TF_CourtesyInspectionStaff=ismissing(airport_dataset.CourtesyOfInspectionStaff);
TF_CourtesySecurityStaff=ismissing(airport_dataset.CourtesyOfSecurityStaff);
TF_ThoroughnessInspection=ismissing(airport_dataset.ThoroughnessOfSecurityInspection);
TF_WaitTimeInspection=ismissing(airport_dataset.WaitTimeOfSecurityInspection);
TF_FeelingSafetySecurity=ismissing(airport_dataset.FeelingOfSafetyAndSecurity);
TF_EoFindingWay=ismissing(airport_dataset.EaseOfFindingYourWayThroughTheAirport);
TF_FlightInformationScreens=ismissing(airport_dataset.FlightInformationScreens);
TF_WalkingDistanceTerminal=ismissing(airport_dataset.WalkingDistanceInsideTerminal);
TF_EoMakingConnections=ismissing(airport_dataset.EaseOfMakingConnections);
TF_CourtesyAirportStaff=ismissing(airport_dataset.CourtesyOfAirportStaff);
TF_Restaurants=ismissing(airport_dataset.Restaurants);
TF_RestaurantsVfM=ismissing(airport_dataset.Restaurants_valueForMoney_);
TF_AvailATMS=ismissing(airport_dataset.AvailabilityOfBanks_ATM_moneyChanging);
TF_ShoppingFacilities=ismissing(airport_dataset.ShoppingFacilities);
TF_ShoppingFacilitiesVfM=ismissing(airport_dataset.ShoppingFacilities_valueForMoney_);
TF_InternetAccess=ismissing(airport_dataset.InternetAccess);
TF_BussinessExecutiveLounges=ismissing(airport_dataset.Business_executiveLounges);
TF_AvailWashRooms=ismissing(airport_dataset.AvailabilityOfWashrooms);
TF_CleannessWashrooms=ismissing(airport_dataset.CleanlinessOfWashrooms);
TF_ComfortWaitingGateArea=ismissing(airport_dataset.ComfortOfWaiting_gateAreas);
TF_CleannessTerminal=ismissing(airport_dataset.CleanlinessOfAirportTerminal);
TF_AmbienceAirprot=ismissing(airport_dataset.AmbienceOfAirport);
TF_ArrivalsPassportInspection=ismissing(airport_dataset.ArrivalsPassportAndVisaInspection);
TF_SpeedBaggage=ismissing(airport_dataset.SpeedOfBaggageDelivery);
TF_CustomsInspection=ismissing(airport_dataset.CustomsInspection);
TF_OverallSatisfaction=ismissing(airport_dataset.OverallSatisfaction);

airport_dataset=fillmissing(airport_dataset,"movmedian",10);
airport_dataset(1:34)=round(airport_dataset.Variables,0);